#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.ORM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNEVERSITY.MDF")]
	public partial class UniversityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDarse(Darse instance);
    partial void UpdateDarse(Darse instance);
    partial void DeleteDarse(Darse instance);
    partial void Insertentekhab(entekhab instance);
    partial void Updateentekhab(entekhab instance);
    partial void Deleteentekhab(entekhab instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertOstad(Ostad instance);
    partial void UpdateOstad(Ostad instance);
    partial void DeleteOstad(Ostad instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    #endregion
		
		public UniversityDataContext() : 
				base(global::University.Properties.Settings.Default.UNEVERSITY_MDFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UniversityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniversityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniversityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UniversityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Darse> Darses
		{
			get
			{
				return this.GetTable<Darse>();
			}
		}
		
		public System.Data.Linq.Table<entekhab> entekhabs
		{
			get
			{
				return this.GetTable<entekhab>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Ostad> Ostads
		{
			get
			{
				return this.GetTable<Ostad>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Darse")]
	public partial class Darse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_dars;
		
		private string _name;
		
		private System.Nullable<int> _tedad_vahed;
		
		private string _type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_darsChanging(int value);
    partial void Onid_darsChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Ontedad_vahedChanging(System.Nullable<int> value);
    partial void Ontedad_vahedChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public Darse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dars", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_dars
		{
			get
			{
				return this._id_dars;
			}
			set
			{
				if ((this._id_dars != value))
				{
					this.Onid_darsChanging(value);
					this.SendPropertyChanging();
					this._id_dars = value;
					this.SendPropertyChanged("id_dars");
					this.Onid_darsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedad_vahed", DbType="Int")]
		public System.Nullable<int> tedad_vahed
		{
			get
			{
				return this._tedad_vahed;
			}
			set
			{
				if ((this._tedad_vahed != value))
				{
					this.Ontedad_vahedChanging(value);
					this.SendPropertyChanging();
					this._tedad_vahed = value;
					this.SendPropertyChanged("tedad_vahed");
					this.Ontedad_vahedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.entekhab")]
	public partial class entekhab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_student;
		
		private System.Nullable<int> _id_ostad;
		
		private System.Nullable<int> _id_dars;
		
		private System.Nullable<int> _tedad_vahed;
		
		private System.Nullable<int> _nomre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_studentChanging(System.Nullable<int> value);
    partial void Onid_studentChanged();
    partial void Onid_ostadChanging(System.Nullable<int> value);
    partial void Onid_ostadChanged();
    partial void Onid_darsChanging(System.Nullable<int> value);
    partial void Onid_darsChanged();
    partial void Ontedad_vahedChanging(System.Nullable<int> value);
    partial void Ontedad_vahedChanged();
    partial void OnnomreChanging(System.Nullable<int> value);
    partial void OnnomreChanged();
    #endregion
		
		public entekhab()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_student", DbType="Int")]
		public System.Nullable<int> id_student
		{
			get
			{
				return this._id_student;
			}
			set
			{
				if ((this._id_student != value))
				{
					this.Onid_studentChanging(value);
					this.SendPropertyChanging();
					this._id_student = value;
					this.SendPropertyChanged("id_student");
					this.Onid_studentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ostad", DbType="Int")]
		public System.Nullable<int> id_ostad
		{
			get
			{
				return this._id_ostad;
			}
			set
			{
				if ((this._id_ostad != value))
				{
					this.Onid_ostadChanging(value);
					this.SendPropertyChanging();
					this._id_ostad = value;
					this.SendPropertyChanged("id_ostad");
					this.Onid_ostadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dars", DbType="Int")]
		public System.Nullable<int> id_dars
		{
			get
			{
				return this._id_dars;
			}
			set
			{
				if ((this._id_dars != value))
				{
					this.Onid_darsChanging(value);
					this.SendPropertyChanging();
					this._id_dars = value;
					this.SendPropertyChanged("id_dars");
					this.Onid_darsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedad_vahed", DbType="Int")]
		public System.Nullable<int> tedad_vahed
		{
			get
			{
				return this._tedad_vahed;
			}
			set
			{
				if ((this._tedad_vahed != value))
				{
					this.Ontedad_vahedChanging(value);
					this.SendPropertyChanging();
					this._tedad_vahed = value;
					this.SendPropertyChanged("tedad_vahed");
					this.Ontedad_vahedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomre", DbType="Int")]
		public System.Nullable<int> nomre
		{
			get
			{
				return this._nomre;
			}
			set
			{
				if ((this._nomre != value))
				{
					this.OnnomreChanging(value);
					this.SendPropertyChanging();
					this._nomre = value;
					this.SendPropertyChanged("nomre");
					this.OnnomreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nuser;
		
		private string _npass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnuserChanging(string value);
    partial void OnnuserChanged();
    partial void OnnpassChanging(string value);
    partial void OnnpassChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nuser", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nuser
		{
			get
			{
				return this._nuser;
			}
			set
			{
				if ((this._nuser != value))
				{
					this.OnnuserChanging(value);
					this.SendPropertyChanging();
					this._nuser = value;
					this.SendPropertyChanged("nuser");
					this.OnnuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_npass", DbType="NVarChar(50)")]
		public string npass
		{
			get
			{
				return this._npass;
			}
			set
			{
				if ((this._npass != value))
				{
					this.OnnpassChanging(value);
					this.SendPropertyChanging();
					this._npass = value;
					this.SendPropertyChanged("npass");
					this.OnnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ostad")]
	public partial class Ostad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_ostad;
		
		private string _name;
		
		private string _family;
		
		private string _id_meli;
		
		private string _sh_sh;
		
		private string _madrak;
		
		private string _mobile;
		
		private string _tel;
		
		private string _address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_ostadChanging(int value);
    partial void Onid_ostadChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfamilyChanging(string value);
    partial void OnfamilyChanged();
    partial void Onid_meliChanging(string value);
    partial void Onid_meliChanged();
    partial void Onsh_shChanging(string value);
    partial void Onsh_shChanged();
    partial void OnmadrakChanging(string value);
    partial void OnmadrakChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public Ostad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ostad", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_ostad
		{
			get
			{
				return this._id_ostad;
			}
			set
			{
				if ((this._id_ostad != value))
				{
					this.Onid_ostadChanging(value);
					this.SendPropertyChanging();
					this._id_ostad = value;
					this.SendPropertyChanged("id_ostad");
					this.Onid_ostadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family", DbType="NVarChar(50)")]
		public string family
		{
			get
			{
				return this._family;
			}
			set
			{
				if ((this._family != value))
				{
					this.OnfamilyChanging(value);
					this.SendPropertyChanging();
					this._family = value;
					this.SendPropertyChanged("family");
					this.OnfamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_meli", DbType="Char(10)")]
		public string id_meli
		{
			get
			{
				return this._id_meli;
			}
			set
			{
				if ((this._id_meli != value))
				{
					this.Onid_meliChanging(value);
					this.SendPropertyChanging();
					this._id_meli = value;
					this.SendPropertyChanged("id_meli");
					this.Onid_meliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh_sh", DbType="Char(5)")]
		public string sh_sh
		{
			get
			{
				return this._sh_sh;
			}
			set
			{
				if ((this._sh_sh != value))
				{
					this.Onsh_shChanging(value);
					this.SendPropertyChanging();
					this._sh_sh = value;
					this.SendPropertyChanged("sh_sh");
					this.Onsh_shChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madrak", DbType="NVarChar(50)")]
		public string madrak
		{
			get
			{
				return this._madrak;
			}
			set
			{
				if ((this._madrak != value))
				{
					this.OnmadrakChanging(value);
					this.SendPropertyChanging();
					this._madrak = value;
					this.SendPropertyChanged("madrak");
					this.OnmadrakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="Char(11)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="Char(8)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_student;
		
		private string _name;
		
		private string _family;
		
		private string _id_meli;
		
		private string _sh_sh;
		
		private string _vorodi;
		
		private string _maghtae;
		
		private string _mobile;
		
		private string _tel;
		
		private string _address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_studentChanging(int value);
    partial void Onid_studentChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfamilyChanging(string value);
    partial void OnfamilyChanged();
    partial void Onid_meliChanging(string value);
    partial void Onid_meliChanged();
    partial void Onsh_shChanging(string value);
    partial void Onsh_shChanged();
    partial void OnvorodiChanging(string value);
    partial void OnvorodiChanged();
    partial void OnmaghtaeChanging(string value);
    partial void OnmaghtaeChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_student", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_student
		{
			get
			{
				return this._id_student;
			}
			set
			{
				if ((this._id_student != value))
				{
					this.Onid_studentChanging(value);
					this.SendPropertyChanging();
					this._id_student = value;
					this.SendPropertyChanged("id_student");
					this.Onid_studentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family", DbType="NVarChar(50)")]
		public string family
		{
			get
			{
				return this._family;
			}
			set
			{
				if ((this._family != value))
				{
					this.OnfamilyChanging(value);
					this.SendPropertyChanging();
					this._family = value;
					this.SendPropertyChanged("family");
					this.OnfamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_meli", DbType="Char(10)")]
		public string id_meli
		{
			get
			{
				return this._id_meli;
			}
			set
			{
				if ((this._id_meli != value))
				{
					this.Onid_meliChanging(value);
					this.SendPropertyChanging();
					this._id_meli = value;
					this.SendPropertyChanged("id_meli");
					this.Onid_meliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sh_sh", DbType="Char(5)")]
		public string sh_sh
		{
			get
			{
				return this._sh_sh;
			}
			set
			{
				if ((this._sh_sh != value))
				{
					this.Onsh_shChanging(value);
					this.SendPropertyChanging();
					this._sh_sh = value;
					this.SendPropertyChanged("sh_sh");
					this.Onsh_shChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorodi", DbType="Char(4)")]
		public string vorodi
		{
			get
			{
				return this._vorodi;
			}
			set
			{
				if ((this._vorodi != value))
				{
					this.OnvorodiChanging(value);
					this.SendPropertyChanging();
					this._vorodi = value;
					this.SendPropertyChanged("vorodi");
					this.OnvorodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maghtae", DbType="NVarChar(10)")]
		public string maghtae
		{
			get
			{
				return this._maghtae;
			}
			set
			{
				if ((this._maghtae != value))
				{
					this.OnmaghtaeChanging(value);
					this.SendPropertyChanging();
					this._maghtae = value;
					this.SendPropertyChanged("maghtae");
					this.OnmaghtaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="Char(11)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="Char(8)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
